### ISSUE TITLE
Meeting time

### ISSUE THREAD

**Issue by vtao1989** [TroyVan/STAT-8051-Project#10]
Hi Tory. Four of us discussed and we found that tomorrow 4 - 5 pm is a good time for a meeting. Are you available during that time? I heard that you live nearby. Hopefully, it works for you. Thanks.

_Originally posted by @vtao1989 in https://github.com/TroyVan/STAT-8051-Project/issues/7#issuecomment-553585145_

**Comment by TroyVan** [comment]
Very well, I will send out Google Calendar event invitations to make it official. Does anyone know any good meeting places? We may need a computer if we are to do anything computation-intensive.

Please continue to indicate your future availability in #7 so that future meetings can be called quickly.

**Comment by matthewfazio** [comment]
Hi all, currently we are planning to meet in the PhD office meeting room. You can access the room by finding Dr. Cook's office then looking for the door with the code lock. I will wait outside and let people in as they come. If computers are needed, the computer lab is next door, or we can use a laptop if applicable.

**Comment by TroyVan** [comment]
@matthewfazio Building and room number?

**Comment by matthewfazio** [comment]
Ford 350

**Comment by vtao1989** [comment]
Thanks, Mat!
