### ISSUE TITLE
First try with logit model

### ISSUE THREAD

**Issue by vtao1989** [TroyVan/STAT-8051-Project#11]
Hi team,

I have just tested the submission system by using a simple logit model and beat the benchmark.
The model is,

`glm(convert_ind ~ AMT + DISC + credit_score + factor(num_loaned_veh) + factor(num_owned_veh) + factor(num_leased_veh), data = train, family = 'binomial')`

where AMT and DISC are the coded quoted_amt and discount.

Several things I think is important during my last submission test,
- Can not have NA in the predictions
- Only need to contain policy_id and conv_prob
- conv_prob is the probability, not 0 or 1.

Tao

**Comment by TroyVan** [comment]
Great, now the leaderboard shows my name alone. We really need to get a team name figured out; my suggestion was only intended as a fallback, since it's not that good of a name.

Because this model falls under #4, I'm transferring this post there. Any further discussion should be made under #4. Different GLM models do not compete with each other during the method selection stage: they're grouped under the same umbrella that is #4 and compete with completely different approaches.

**Comment by vtao1989** [comment]
The AUC for the train part is 0.5821, very close to the submission score. 

We could firstly fit the training dataset with a cross-validation method (10 might be good for this case) to test our model assumptions and then submit the model result with the best AUC.
