### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by vtao1989** [TroyVan/STAT-8051-Project#21]
I have finished the data cleaning. The dataset is stored at **tao.RData**.

The description of the data cleaning is in **variable_description_Tao.md**.

The R file for data cleaning is in **data_cleaning_Tao.R**.

After loading the data, you have two dataset, one for train (including variable called _cv_index_ to indicate its cross validation subset), and the other for test. The dataset contains information merged from drivers and vehicles. I did not code color and brand of the vehicles, but I am glad to do it later.

Please let me know if you have any questions.

**Comment by hezhou1354** [comment]
Hi Tao,

Great job! I think most of the transformations are reasonable, but taking average for categorical variables still doesn't make sense to me. So I have some suggestions:

Drivers.csv:
1. For "gender", I suggest you transform it to two variables "num_male" and "num_female", i.e., counting the number of each gender.
2. For "age", since there may be some dependents in a policy, so it's not reasonable to mixture the ages. I suggest that you divide the age into several ranges: "age_10_20", "age_20_30", so on and so forth, then count the number in each range.

Vehicles.csv:
For "car_model", maybe we could only care about the brand (there are 19 brands in total), and count the number of each brand? I'm not sure.

**Comment by vtao1989** [comment]
@hezhou1354 Good! I will do it today.
